name: feliz_sabado
description: Aplicación que te ayuda a recibir el Sábado.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  equatable: ^2.0.3
  iconsax: ^0.0.8
  salomon_bottom_bar: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
